server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost2:8762/eureka/,http://localhost3:8763/eureka/

spring:
  application:
    name: eurka-server